In [ ]:
# you can search an array for a certain value and return the indexes that get a match.
# use the where() method.

In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4,5,6,5,6,5,5,5])
b=np.where(a==5)
print(b)

(array([ 4,  6,  8,  9, 10]),)


In [6]:
d=a[b]
print(d)
print(b)

[5 5 5 5 5]
(array([ 4,  6,  8,  9, 10]),)


In [9]:
# find even value
s=np.array([1,2,3,4,5,6,7.8,9])
a=np.where(s%2==0)
print(a)
q=s[a]
print(q)

(array([1, 3, 5]),)
[2. 4. 6.]


In [12]:
# find odd value
w=np.array([44,556,78,45,22,41,4,5,1,12,15,18])
e=np.where(w%2==1)
print(e)
d=w[e]
print(d)

(array([ 3,  5,  7,  8, 10]),)
[45 41  5  1 15]


In [14]:
d=np.array([1,2,4,5,6,0])
a=np.where(d>2)
print(a)
w=d[a]
print(w)

(array([2, 3, 4]),)
[4 5 6]


In [16]:
# search sorted

a=np.array([1,2,4,5,6])
x=np.searchsorted(a,3)
print(x)
print(a)

2
[1 2 4 5 6]


In [17]:
# seacrhmethod
a=np.array([12,14,16,17,18])
b=np.searchsorted(a,15)
print(b)

2


In [18]:
a=np.array([12,14,16,17,18])
b=np.searchsorted(a,16)
print(b)

2


In [20]:
#  side = right
a=np.array([12,14,16,17,18])
b=np.searchsorted(a,17,side='right')
print(b)

4


In [23]:
a=np.array([12,14,16,17,18])
b=np.searchsorted(a,18,side='left')
print(b)

4


In [24]:
a=np.array([1,3,5,7])
x=np.searchsorted(a,[2,4,6])
print(x)

[1 2 3]
