In [1]:
import numpy as np

In [ ]:
# sorting means putting element in an ordered sequence.
# ordered sequence is numeric,alphabetial,ascending or descending order

In [2]:
a=np.array([5,7,2,1,0,2,8,6, 9])
print(np.sort(a))

[0 1 2 2 5 6 7 8 9]


In [3]:
b=np.array(['roshani','sakshi','amol','divya','savi'])
print(np.sort(b))

['amol' 'divya' 'roshani' 'sakshi' 'savi']


In [4]:
s=np.array([True,False,False,True,True,False])
print(np.sort(s))

[False False False  True  True  True]


In [5]:
a=np.array([[4,2,3],[5,0,2]])
print(np.sort(a))

[[2 3 4]
 [0 2 5]]
