In [1]:
import numpy as np

In [2]:
a=np.array([42,45,65,40,48])
y=np.array([True,False,True,False,True])
n=a[y]
print(n)

[42 65 48]


In [5]:
# create filter array that will return only values higher than 12

a=np.array([1,7,8,45,12,29,6,56])

filter_arr =[]

for i in a:
    if i>12:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
    
n=a[filter_arr]   

print(filter_arr)
print(n)

[False, False, False, True, False, True, False, True]
[45 29 56]


In [6]:
a=np.array([1,2,3,4,5,6,7,8,9,10])

b=[]

for i in a:
    if i%2==0:
        b.append(True)
    else:
        b.append(False)
    
s=a[b]
print(s)
print(b)

[ 2  4  6  8 10]
[False, True, False, True, False, True, False, True, False, True]


In [8]:
#  create a filter array that will return only values less than 0

a=np.array([-7,8,9,56,67,-8,6,-9])
filter_arr=a<0
n=a[filter_arr]
print(filter_arr)
print(n)

[ True False False False False  True False  True]
[-7 -8 -9]


In [9]:
#  create a filter array that will return only values equal to 56

a=np.array([-7,8,9,56,56,56,56,67,-8,6,-9])
filter_arr=a==56
n=a[filter_arr]
print(filter_arr)
print(n)

[False False False  True  True  True  True False False False False]
[56 56 56 56]
