In [14]:
import numpy as np
# random number does not mean a different number every time .

In [10]:
# generate a random integer from 0 to 100
from numpy import random
x = random.randint(100)
print(x)

76


In [13]:
# generate a random float from 0 to 1 ------ by defualt between 0 and 1
#from numpy import random
x = random.rand()
print(x)

0.6726910191126191


In [16]:
# generate a random array from 0 to 100 integer value  and 5 random number  [1D]
from numpy import random
x = random.randint(100,size=5)  
print(x)

[25 23 15 83 84]


In [17]:
# generate a random array from 0 to 100 integer value  and 5 random number  [2D]
from numpy import random
x = random.randint(100,size=(3,5))  
print(x)

[[24 47 89 68  3]
 [60 30 33 97 72]
 [39 37 89 35 28]]


In [20]:
# float
x=random.rand(5)
print(x)

[0.38961088 0.70843454 0.3798344  0.37780472 0.6714038 ]


In [21]:
y=random.rand(3,5)
print(y)

[[0.78817379 0.28302302 0.13890624 0.12078246 0.15426091]
 [0.18904533 0.85369242 0.16810384 0.2721037  0.69961975]
 [0.27373988 0.5404327  0.77357148 0.56821956 0.71607901]]


In [28]:
# generate random number array from array
# choice()

x=random.choice ([1,2,5,6,7])
print(x)

2


In [30]:
y=random.choice([8,9,6,5],size=(3,5))
y

array([[5, 9, 9, 9, 9],
       [6, 9, 5, 6, 8],
       [9, 5, 6, 5, 8]])