In [ ]:
import numpy as np 

#------------------------------------------------------------------------------------------------------------------------------
l=[1,2,4,21,6] # list may comma hota hai  // op :[1, 2, 4, 21, 6]
print(l)

n=np.array([1,2,3,4,5,6])   # array may comma nahi hota hai  // op : [1 2 3 4 5 6]
print(n)

#------------------------------------------------------------------------------------------------------------------------------

l2=[1,2,4,5,6,'7']   # list may different datatype store hote hai [1, 2, 4, 5, 6, '7']
print(l2)

n=np.array([1,2,4,5,6,'7'])  # only one datatype store hota hai  but differnt datatype may convert hota hai // op :  ['1' '2' '4' '5' '6' '7']
print(n)                     # priority  bases   --- int --- float --- string 

#------------------------------------------------------------------------------------------------------------------------------

: 

In [ ]:
a=np.array([1,2,3,4,5])

In [ ]:
print(a)
a.ndim
a.size
a.shape
a.dtype
a.reshape(5,1)

In [ ]:
b=np.array([[1,2,2],[2,3,4],[6,7,8]])
#print(b)
b.ndim
b.size
b.shape
b.dtype
b.reshape(1,9)
#b.reshape(9,1)
#b.reshape(3,3)

In [ ]:
c=np.array([[[1,2,3],[6,78,5]]])
print(c)
c.ndim
c.size
c.shape
c.dtype
c.reshape(3,2)
c.reshape(1,6)
c.reshape(6,1)
c.reshape(2,3)

In [ ]:
d=np.array([[[[1,2,3],[5,6,7],[9,0,6],[2,4,5]]]])
print(d)
d.ndim
d.size
d.shape
d.dtype
s=d.reshape(3,4)
s
print(s)
d.reshape(2,6)


[[[[1 2 3]
   [5 6 7]
   [9 0 6]
   [2 4 5]]]]
[[1 2 3 5]
 [6 7 9 0]
 [6 2 4 5]]


In [ ]:
f=np.array([[[[[[2,4,5]]]]]])
print(f)
f.ndim
f.size
f.shape
f.dtype
f.reshape(3,1)

: 

In [ ]:
e=np.array([[[[[2,6,22,12,42],[24,2,12,2,1],[22,2,21,21,2]]]]])
print(e)
e.ndim
e.size
e.shape
e.dtype
e.reshape(1,15)
d=e.reshape(5,3)
print(d)

: 

In [ ]:
n=np.array([[[[[[1,2,4,4,45,6,8],[1,4,5,6,7,5,4]]]]]])
print(n)
n.ndim
n.size
n.dtype
n.shape
n.reshape(2,7)
w=n.reshape(7,2)
print(w)

: 

In [ ]:
r=np.array([[[[[[[[1,2,2,2,4,7],[4,5,6,54,1,2],[5,6,4,5,6,72],[2,4,5,6,7,6],[2,4,4,5,6644,4]]]]]]]])
print(r)
r.ndim
r.size
r.dtype
r.shape
t=r.reshape(2,15)
print(t)