In [2]:
import numpy as np

In [ ]:
l=[1,2,4,21,6]   #  list may add element hota hai  // op  : [1, 2, 4, 21, 6, 2, 1, 4, 5, 6]
l2=[2,1,4,5,6]
print(l+l2)

n=np.array([1,2,3,4,5,6])    #  array may add element hota hai but position per element add hota hai // op :[ 2  4  6  8 10 12]
n1=np.array([1,2,3,4,5,6])
print(n+n1)



[1, 2, 4, 21, 6, 2, 1, 4, 5, 6]
[ 2  4  6  8 10 12]


In [52]:
n=np.array([1,2,3,4,5,6])   
n1=np.array([1,2,3,4,5,6])
print(n+n1)
print(n-n1)
print(n*n1)
print(n/n1)
print(n%n1)

[ 2  4  6  8 10 12]
[0 0 0 0 0 0]
[ 1  4  9 16 25 36]
[1. 1. 1. 1. 1. 1.]
[0 0 0 0 0 0]


In [ ]:
 #  use function 

n=np.array([1,2,4,5,6])      
print(n)
np.add(n,5)            #  array may per element 5 se increase
np.subtract(n,1)       #  array may per element 1 se decrease
np.multiply(n,5)       #  array may per element 5 se multiply 
np.divide(n,5)         #  array may per element 5 se divide
np.mod(n,5)            #  array may per element 5 se modulus


[1 2 4 5 6]


array([1, 2, 4, 0, 1])