In [ ]:
import numpy as np

# Slicing in python means taking elements from one given index to another given index.
# [start:end:step].


In [2]:
b=np.array([1,2,3,4])
print(b[0:4])

[1 2 3 4]


In [3]:
b=np.array([[1,2,3,4],[7,8,9,4]])
print(b[0,0:3],b[1,0:3])

[1 2 3] [7 8 9]


In [4]:
s=np.array([[1,2,4,5],[2,4,5,6],[4,5,6,6]])
print(s[0,0:4],s[1,0:4],s[2,0:4])

[1 2 4 5] [2 4 5 6] [4 5 6 6]


In [5]:
b=np.array([[1,2,3,4],[4,5,6,4]])
print(b[0,1:4],b[1,1:4])

[2 3 4] [5 6 4]


In [ ]:
# without end 
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])

[5 6 7]


In [13]:
#  negative slicing
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-7:-1])


[1 2 3 4 5 6]


In [7]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])


[5 6]


In [14]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[0:-1])


[1 2 3 4 5 6]


In [ ]:
#  without start
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:-1])


[1 2 3 4 5 6]


In [16]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:])


[1 2 3 4 5 6 7]


In [ ]:
#  negative slicing
ar=np.array([1,2,3,4,5,6,7,8])
print(ar[-4:-1])

[5 6 7]


In [4]:
ar=np.array([1,2,3,4,5,6,7,8])
print(ar[-4: ])

[5 6 7 8]


In [ ]:
ar=np.array([1,2,3,4,5,6,7,8])
print(ar[-4:-1])

In [ ]:
#  step follow for slicing

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [6]:
# without start and end
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

[1 3 5 7]


In [7]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [8]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:])

[ 7  8  9 10]


In [9]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0, 1:4])

[2 3 4]


In [10]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0, 1:4],arr[1,1:4])

[2 3 4] [7 8 9]
