In [2]:
import numpy as np


In [3]:
# Reshaping arrays
# Reshaping means changing the shape of an array.


In [4]:

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = a.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [5]:
b=np.array([[1,2,4,5],[5,6,7,8]])
print(b.reshape(1,8))

[[1 2 4 5 5 6 7 8]]


In [7]:
b=np.array([[1,2,4,5],[5,6,7,8]])
print(b.reshape(8,1))

[[1]
 [2]
 [4]
 [5]
 [5]
 [6]
 [7]
 [8]]


In [ ]:
#  2 array , 3 row , 2 each element 
r = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

n = r.reshape(2, 3, 2)

print(n)


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [13]:

arr = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]])

newarr = arr.reshape(2, 3, 2)

print(newarr)


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
# -1 is use one dimensional kiya hai
a=np.array([[1,2,3],[4,5,6]])
n=a.reshape(-1)
print(n)

[1 2 3 4 5 6]
