In [1]:
import numpy as np

In [ ]:
# iterating 1D array
a=np.array([1,2,3,4,5,6,7,8])

for x in a:
    print(x)

1
2
3
4
5
6
7
8


In [3]:
# iterating 2D array
a=np.array([[1,2,3],[4,5,6]])
for x in a:
    print(x)

[1 2 3]
[4 5 6]


In [7]:
a=np.array([[1,2,3],[4,5,6]])
for i in a:
    for l in i:
        print(l)

1
2
3
4
5
6


In [8]:
# 3D iterating
b=np.array([[[1,2,3],[5,6,4]],[[7,8,9],[10,11,12]]])
for x in b:
    print(x)

[[1 2 3]
 [5 6 4]]
[[ 7  8  9]
 [10 11 12]]


In [9]:
b=np.array([[[1,2,3],[5,6,4]],[[7,8,9],[10,11,12]]])
for x in b:
    for y in x:
        print(y)

[1 2 3]
[5 6 4]
[7 8 9]
[10 11 12]


In [10]:
b=np.array([[[1,2,3],[5,6,4]],[[7,8,9],[10,11,12]]])
for x in b:
    for y in x:
        for z in y:
            print(z)

1
2
3
5
6
4
7
8
9
10
11
12


In [ ]:
# iterating arrays using nditer()

b=np.array([[[1,2,3],[5,6,4]],[[7,8,9],[10,11,12]]])
for x in np.nditer (b):
    print(x)
 
    

1
2
3
5
6
4
7
8
9
10
11
12


In [ ]:
#  iterating with different step size``
a=np.array([[1,2,3,4],[5,6,7,8]])
for x in np.nditer (a[ : , : :2]):
    print(x)

1
3
5
7


In [ ]:
# enumerated iteration using ndenumerate()
# enumeration means mentioning sequence number of something one by one 
#  1D  ndenumerate
a=np.array([1,2,3])
for idx,x in np.ndenumerate (a):
    print(idx,x)

(0,) 1
(1,) 2
(2,) 3


In [14]:
# 2D ndenumerate
a=np.array([[1,2,3],[6,7,8]])
for idx,x in np.ndenumerate (a):
    print(idx,x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 6
(1, 1) 7
(1, 2) 8
