In [1]:
import numpy as np

In [ ]:
# joining means putting content of two or more arrays in a single array.
#  join two array

In [ ]:
# joining array with conatenate function
a1=np.array([1,2,3])
a2=np.array([4,5,6])
a3=np.concatenate((a1,a2))
print(a3)

[1 2 3 4 5 6]


In [5]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
a3=np.concatenate((a1,a2),axis=0)
print(a3)

[1 2 3 4 5 6]


In [11]:
a1=np.array([[1,2,3]])
a2=np.array([[4,5,6]])
a3=np.concatenate((a1,a2),axis=1)
print(a3)

[[1 2 3 4 5 6]]


In [13]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
arr=np.concatenate((arr1,arr2),axis=0)
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [14]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
arr=np.concatenate((arr1,arr2),axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [15]:
# joining arrays using stack functions

arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
arr=np.stack((arr1,arr2),axis=0)
print(arr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [16]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
arr=np.stack((arr1,arr2),axis=1)
print(arr)

[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [ ]:
# two type of stack
# vstack   : vertical stack
# hstack   : horizontal stack

In [19]:
#  stacking along rows

arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
arr=np.hstack((arr1,arr2))
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [20]:
#  stacking along columns

arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
arr=np.vstack((arr1,arr2))
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [21]:
#  stacking along height (depth)

arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
arr=np.dstack((arr1,arr2))
print(arr)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]
